### ISSUE TITLE
Styling for TabBar

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble-react#226]
**Is your feature request related to a problem? Please describe.**
I want to style the TabBar heading styles like backgroundColors, active non active tabbar, and also adding border borderRadius etc.

**Describe the solution you'd like**
Something like this should be achievable.
<img width="407" alt="Screenshot 2023-12-06 at 6 24 40 PM" src="https://github.com/EnsembleUI/ensemble-react/assets/62849614/e8513746-5c7d-45c8-8d50-436284f4b0da">

**Describe alternatives you've considered**

**Additional context**

**Comment by evshi** [comment]
@sibteali786 for this please use a ToggleButton that @anserwaseem implemented with a Conditional

**Comment by sagardspeed2** [comment]
@evshi @sibteali786 for this design screenshot that you added here for the reference, that is acheivable but not using the tabBar,
There is complete unique widget for this in antd component collation, called `segmented`.

Here is the refereal link for that.
https://ant.design/components/segmented

**Comment by evshi** [comment]
@sagardspeed2 there are other instances of tabs where we require styling 
![image](https://github.com/EnsembleUI/ensemble-react/assets/4132143/10f05220-b977-43fc-a464-f423016d8a4f)

Can you look into how we can best expose the tab styling?

**Comment by sagardspeed2** [comment]
@evshi according your given example and documentation of antd, for your usecase we can use third type of tabs that is radio.button, because as per the exposed API of tabs component of the antd, we can't expose more styles on the tabs. like setting background colors, border, border radius are not possible on the tabs.

reference: https://ant.design/components/tabs#tabs
