### ISSUE TITLE
Dropdown value is not initialized correctly

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#470]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by evshi** [comment]
https://github.com/atlas-health/atlas-navigator-ui/pull/193#discussion_r1525137014

**Comment by sagardspeed2** [comment]
The dropdown initially displays the correct value, but its options aren't ready due to our use of useMemo. This means that when the dropdown is rendered, it doesn't have any options yet. Therefore, even though we set a defaultValue, it appears without any options. Later, when the options are ready and added to the dropdown, it can properly match the given value and display its label.
